#!/bin/bash

# Wrapper around ansible-playbook that sets the terminal's title

ANSIBLE_FORCE_COLOR=true stdbuf -i0 -o0 -e0 ansible-playbook "${@}" | tee /proc/$$/fd/1 | while IFS='' read -r line; do
	if [[ "${line}" =~ ^TASK\ \[ ]]; then
		title="$(echo "${line}" | cut -d'[' -f2 | cut -d']' -f1)"
		echo -ne '\033k['"${title}"']\033\\'
	fi
done
