#!/usr/bin/env bash

set -euo pipefail

unloadRecursive() {
	# Unload dependants
	deptext="$(lsmod | grep "^${1}" | awk '{print $4}' || :)"
	IFS=, read -r -a deps <<< "${deptext}"
	for dep in "${deps[@]}"; do
		unloadRecursive "${dep}"
	done
	# Special handling for iptables garbage
	if [ "${1}" = iptable_filter ]; then
		"${ipt}" -F
		"${ipt}" -X
	fi
	if [ "${1}" = ip6table_filter ]; then
		"${ip6t}" -F
		"${ip6t}" -X
	fi
	if [ "${1}" = iptable_nat ]; then
		"${ipt}" -t nat -F
		"${ipt}" -t nat -X
	fi
	if [ "${1}" = ip6table_nat ]; then
		"${ip6t}" -t nat -F
		"${ip6t}" -t nat -X
	fi
	if [ "${1}" = iptable_mangle ]; then
		"${ipt}" -t mangle -F
		"${ipt}" -t mangle -X
	fi
	if [ "${1}" = ip6table_mangle ]; then
		"${ip6t}" -t mangle -F
		"${ip6t}" -t mangle -X
	fi

	# Unload the module
	rmmod "${1}" || :
}

ipt="${IPTABLES:-iptables-legacy}"
ip6t="${IP6TABLES:-ip6tables-legacy}"
for module in "${@}"; do
	echo "Unloading ${module}"
	unloadRecursive "${module}"
done
